### ISSUE TITLE
Regarding the Timing of Prototype Updates

### ISSUE THREAD

**Issue by zhaihaotian** [zhangce01/DPE-CLIP#1]
In Section 3.3 of the paper, the last paragraph states: “After optimizing the prototypes for each test sample, we evolve the online textual prototypes \( t \) as described in Equation (3), and also update the priority queues to re-compute the visual prototypes \( v \). The evolved prototype sets then serve as the initialization for the next test sample, progressively enhancing generalization capability during test-time adaptation.”

Based on this description, it seems the sequence should be to perform “Prototype Residual Learning” first, followed by “Textual Prototype Evolution” and then “Visual Prototype Evolution.” However, in the actual code implementation, the sequence appears to be “Visual Prototype Evolution” first, followed by “Prototype Residual Learning,” and finally “Textual Prototype Evolution.”

Could you kindly explain why the actual implementation order in the code differs from the description in the paper? And which way is right? Thank you so much !

**Comment by zhangce01** [comment]
Thank you for your interest in this work!

Sorry for the late reply and also for the confusion cause by the inconsistency. For clearer presentation in the paper, we treat the visual prototype evolution for the next sample as the pre-process for residual learning, therefore we can symmetrically introduce both textual and visual prototype evolution. You can interpret the process as performing residual learning for sample t, textual prototype evolution for sample t, and visual prototype evolution for sample t+1. Framing it this way aligns with the explanation in the paper.
